Fix error C2445
result type of conditional expression is ambiguous: types 'const wchar_t [5]' and 'wxString' can be converted to multiple common types [D:\a\Antares_Simulator\Antares_Simulator\_build\ui\simulator\antares-8.5-ui-simulator.vcxproj]