Bump OR-Tools 9.2 -> 9.5, fix random compilation errors in Windows (#1167)
* Bump OR-Tools 9.2 -> 9.5

* Remove typedef struct, use C++ declarations instead

* Fix error C2445

result type of conditional expression is ambiguous: types 'const wchar_t [5]' and 'wxString' can be converted to multiple common types [D:\a\Antares_Simulator\Antares_Simulator\_build\ui\simulator\antares-8.5-ui-simulator.vcxproj]

* rte1.0 -> rte1.1

* Bump to 9.5-rte2.0

* Fix error C2445

result type of conditional expression is ambiguous: types 'const wchar_t [5]' and 'wxString' can be converted to multiple common types [D:\a\Antares_Simulator\Antares_Simulator\_build\ui\simulator\antares-8.5-ui-simulator.vcxproj]